---
# tasks file for ansible-role-ssh

- include_vars: "{{ ansible_os_family }}.yml"

- name: Create ssh_config_file
  template:
    src: ssh_config.j2
    dest: "{{ ssh_config_file }}"
    backup: yes
    #validate: echo %s

- name: Manage ssh_known_hosts
  known_hosts:
    path: "{{ ssh_known_hosts_file }}"
    name: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ ssh_known_hosts }}"
